### ISSUE TITLE
输入时存在卡顿

### ISSUE THREAD

**Issue by Grant-S-Z** [guangzhengli/typora-ladder-theme#1]
当使用该模版输入时，存在明显的输入延迟，请问有什么解决方法吗？

**Comment by guangzhengli** [comment]
请问你有修改字体吗，我之前用 woff2 的字体有遇到这个问题，但是我修改成 ttf 后目前没有卡顿的情况

**Comment by Grant-S-Z** [comment]
您好，我看了一下我下载版本的css文件，发现原因应该是typora商店引导下载的版本仍使用woff2字体。刚才我直接git clone仓库，模版是可以正常使用的，谢谢解答～
